#!C:\Users\atorq\OneDrive\Desktop\spc_research_v2\spc_env312\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
